autotrade/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application 
from django.conf.urls import include

urlpatterns += [
    path('main/', include('main.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/main/')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('theories/', views.TheoryListView.as_view(), name='theories'),
    path('theories/<int:pk>', views.TheoryDetailView.as_view(), name='theory-detail'),
    path('indicators/', views.IndicatorListView.as_view(), name='indicators'),
    path('indicators/<int:pk>', views.IndicatorDetailView.as_view(), name='indicator-detail'),
    path('strategies/', views.StrategyListView.as_view(), name='strategies'),
    path('strategies/<int:pk>', views.StrategyDetailView.as_view(), name='strategy-detail'),
    path('methods/', views.Method, name='methods'),
    path('methods/get-data', views.GetData, name='get-data'),
    path('methods/get-method-arg', views.GetMethodArg, name='get-method-arg'),
    path('methods/use-method', views.UseMethod, name='use-method'),
    path('develop/', views.Develop, name='develop'),
    path('develop/get-data', views.GetData, name='get-data'),
    path('develop/get-method-arg', views.GetMethodArg, name='get-method-arg'),
    path('develop/analyze-strategy', views.AnalyzeStrategy, name='analyze-strategy')

]

main/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid 

class Theory(models.Model):
    """
    Model representing a trading theory.
    """
    name = models.CharField(max_length=200, help_text="Enter the name of theory")
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the theory")
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('theory-detail', args=[str(self.id)])

class Indicator(models.Model):
    """
    Model representing a indicator.
    """
    name = models.CharField(max_length=200, help_text="Enter the name of indicator")
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the indicator")
    related = models.ManyToManyField('self', blank=True) 
    
    def display_related(self):
        return ', '.join([ind.name for ind in self.related.all()])
    display_related.short_description = 'Related indicators'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('indicator-detail', args=[str(self.id)])
    
class IndicatorInstance(models.Model):
    """
    A specific indicator.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular indicator")
    indicator = models.ForeignKey(Indicator, on_delete=models.SET_NULL, null=True)
    kwarg = models.CharField(max_length=200, help_text="Enter the dictionary containing indicator-related parameter",
                             null=True, blank=True)
    
    def __str__(self):
        if self.indicator:
            return 'Instance of ' + self.indicator.name
        return 'null'

class Strategy(models.Model):
    """
    Model representing a Strategy (may be related to indicator or theory).
    """
    name = models.CharField(max_length=200, help_text="Enter the name of strategy")
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the strategy")        
    indicator = models.ManyToManyField(Indicator, blank=True) 

    def display_indicator(self):
        return ', '.join([ind.name for ind in self.indicator.all()])
    display_indicator.short_description = 'Related indicators'  
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('strategy-detail', args=[str(self.id)])
    
class StrategyInstance(models.Model):
    """
    Model representing a Strategy (may be related to indicator or theory).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular strategy")
    strategy = models.ForeignKey(Strategy, on_delete=models.SET_NULL, null=True)
    kwarg = models.CharField(max_length=200, help_text="Enter the dictionary containing indicator-related parameter",
                             null=True, blank=True)     
    
    def __str__(self):
        if self.strategy:
            return 'Instance of ' + self.indicator.name
        return 'null'  
    
class Portfolio(models.Model):
    """
    A combination of many single stocks.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular portfolio")
    weights = models.CharField(max_length=200, help_text="Enter an array that has sum = 1")   # later change it to an array container
    symbols = models.CharField(max_length=200, help_text="Enter a list of symbols")  
    
    def __str__(self):
        return self.symbols     
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

main/forms.py
from django import forms
import inspect

class GetDataForm(forms.Form):
    symbol = forms.CharField(help_text="Enter a valid stock symbol", initial='goog')
    start = forms.DateField(help_text="Enter a start date", initial='2011-09-01')
    end = forms.DateField(help_text="Enter an end date", initial='2012-09-09')
    
    INTERVALS = (
        ('1m', '1 minutes'),
        ('2m', '2 minutes'),
        ('5m', '5 minutes'),
        ('15m', '15 minutes'),
        ('30m', '30 minutes'),
        ('60m', '60 minutes'),
        ('90m', '90 minutes'),
        ('1d', '1 day'),
        ('1wk', '1 week'),
        ('1mo', '1 month'),
        ('3mo', '3 months'),
    )
    interval = forms.ChoiceField(choices=INTERVALS, initial='1d', help_text='Select an interval')  

class SelectIndicatorForm(forms.Form):
    from .methods import indicators 
    INDICATORS = [(ele[0], ele[0]) for ele in inspect.getmembers(indicators, inspect.isfunction)]
    indicator = forms.ChoiceField(choices=INDICATORS, help_text='Select an indicator')  
    
class SelectStrategyForm(forms.Form):
    from .methods import strategies 
    STRATEGIES = [(ele[0], ele[0]) for ele in inspect.getmembers(strategies, inspect.isfunction)]
    strategy = forms.ChoiceField(choices=STRATEGIES, help_text='Select a strategy')      
    
class SelectAnalysisForm(forms.Form):
    from .methods import analysis 
    ANALYSIS = [(ele[0], ele[0]) for ele in inspect.getmembers(analysis, inspect.isfunction)]
    analysis = forms.ChoiceField(choices=ANALYSIS, help_text='Select an analysis')   
    
class DevelopInitialForm(forms.Form):
    start = forms.DateField(initial='2011-09-01')
    end = forms.DateField(initial='2012-09-09')
    INTERVALS = (
        ('1m', '1 minutes'),
        ('2m', '2 minutes'),
        ('5m', '5 minutes'),
        ('15m', '15 minutes'),
        ('30m', '30 minutes'),
        ('60m', '60 minutes'),
        ('90m', '90 minutes'),
        ('1d', '1 day'),
        ('1wk', '1 week'),
        ('1mo', '1 month'),
        ('3mo', '3 months'),
    )
    interval = forms.ChoiceField(choices=INTERVALS, initial='1d')      
    
    
    

main/views.py
from .models import Theory, Indicator, Strategy
from django.views import generic
from .methods import functions, indicators, strategies, analysis, toolFuncs

from django.http import JsonResponse
import inspect
from django.shortcuts import render
import json

from .forms import *

def index(request):
    return render(
        request,
        'index.html',
    )
    
class TheoryListView(generic.ListView):
    model = Theory
    
class TheoryDetailView(generic.DetailView):
    model = Theory
    
class IndicatorListView(generic.ListView):
    model = Indicator
    
class IndicatorDetailView(generic.DetailView):
    model = Indicator

class StrategyListView(generic.ListView):
    model = Strategy
    
class StrategyDetailView(generic.DetailView):
    model = Strategy
    
def Develop(request):
    developInitialForm = DevelopInitialForm()
    selectStrategyForm = SelectStrategyForm()
    return render(
        request,
        'develop.html',
        {'developInitialForm': developInitialForm,
         'selectStrategyForm': selectStrategyForm, 
                 }
    )

def Method(request):
    getDataForm = GetDataForm()
    selectIndicatorForm = SelectIndicatorForm()
    selectStrategyForm = SelectStrategyForm()
    selectAnalysisForm = SelectAnalysisForm()
    
    return render(
        request,
        'methods.html',
        {'getDataForm': getDataForm, 
         'selectIndicatorForm': selectIndicatorForm,
         'selectStrategyForm': selectStrategyForm, 
         'selectAnalysisForm': selectAnalysisForm, 
         }
    )
    
   
def GetData(request):
    symbol = request.POST.get('symbol')    
    start = request.POST.get('start')
    end = request.POST.get('end')
    interval = request.POST.get('interval')

# =============================================================================
#     if symbol and start and end and interval:
#         stock = functions.Generic(symbol, start, end, interval)
#         data = stock._data 
#         new_data = dict(data.reset_index())
#         for ele in new_data:
#            new_data[ele] = list(new_data[ele])
#         return JsonResponse(new_data)
#     else:
#         return JsonResponse({'symbol':symbol, 'start':start, 'end':end, 'interval':interval})
# =============================================================================

    stock = functions.Generic(symbol, start, end, interval)    
    data = stock._data 
    new_data = dict(data.reset_index())
    for ele in new_data:
       new_data[ele] = list(new_data[ele])
    
    return JsonResponse(new_data)
    
def GetMethodArg(request):
    Name = request.POST.get('name', None)
    Type = request.POST.get('type', None) 
    
    if Type == 'indicator':
        lib = indicators
    elif Type == 'strategy':
        lib = strategies
    else:
        lib = analysis
        
    for ind in inspect.getmembers(lib, inspect.isfunction):
        if ind[0] == Name:
            arg = ind[1].__code__.co_varnames[:ind[1].__code__.co_argcount]
            arg = [ele for ele in arg if ele!='data']  #remove the input 'data'
            helpText = ind[1].__doc__
            if helpText:
                helpText = [line.strip() for line in helpText.strip().splitlines()]
            # remove useless spaces, split by line 

            return JsonResponse({'arg': arg, 'helpText': helpText})
    
def UseMethod(request):
    requestDic = json.loads(request.body)
    Name = requestDic.get('name', None)
    Type = requestDic.get('type', None)

    if Type == 'indicator':
        lib = indicators
    elif Type == 'strategy':
        lib = strategies
    else:
        lib = analysis

    data = {}
    data['Open'] = requestDic.get('Open', None) 
    data['Close'] = requestDic.get('Close', None)  
    data['High'] = requestDic.get('High', None)  
    data['Low'] = requestDic.get('Low', None)  
    data['Volume'] = requestDic.get('Volume', None)  
    data['Date'] = requestDic.get('Date', None)  

    kwargs = {'data': data}    
    keys = requestDic.keys() - {'name', 'type', 'Open', 'Close', 'High', 
                           'Low', 'Volume', 'Date', 'Adj Close', 'Amount'}
    for key in keys:
        kwargs[key] = eval(requestDic.get(key, None))
                
    for ind in inspect.getmembers(lib, inspect.isfunction):
        if ind[0] == Name:
            output = ind[1](**kwargs)
            return JsonResponse(output)
    
def AnalyzeStrategy(request):
    requestDic = json.loads(request.body)
    Name = requestDic.get('name', None)    
    
    data = {}
    data['Open'] = requestDic.get('Open', None) 
    data['Close'] = requestDic.get('Close', None)  
    data['High'] = requestDic.get('High', None)  
    data['Low'] = requestDic.get('Low', None)  
    data['Volume'] = requestDic.get('Volume', None)  
    data['Date'] = requestDic.get('Date', None)
    
    kwargs = {'data': data}    
    keys = requestDic.keys() - {'name', 'interval', 'symbol', 'Open', 'Close', 'High', 
                           'Low', 'Volume', 'Date', 'Adj Close', 'Amount'}    
    
    for key in keys:
        kwargs[key] = eval(requestDic.get(key, None))
        
    for ind in inspect.getmembers(strategies, inspect.isfunction):
        if ind[0] == Name:
            output = ind[1](**kwargs)
            
            equity = output['equity']['data']
            positions = output['positions']['data']
            ordersData = output['ordersData']['data']
            
            data['Interval'] = requestDic.get('interval', None)
            data['Symbol'] = requestDic.get('symbol', None)            
            result = toolFuncs.StrategyAnalyses(data, equity, positions, ordersData)
            return JsonResponse(result)
        
        
        
    

main/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Technical Analysis</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script src="{% static 'js/echarts/incubator-echarts-master/dist/echarts.min.js' %}"></script>  
  <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>
  <div id="topnav">
    {% block topnav %}{% endblock %}
  </div>
  
  <div id="content">
    {% block content %}{% endblock %}
  </div>
  
<script>
window.onscroll = function() {myFunction()};

var topnav = document.getElementById("topnav");
var sticky = topnav.offsetTop;

function myFunction() {
  if (window.pageYOffset >= sticky) {
    topnav.classList.add("sticky")
  } else {
    topnav.classList.remove("sticky");
  }
}
</script>  
</body>
</html>

main/templates/develop.html
{% extends "base_generic.html" %}

{% block topnav %}  
    <a href="{% url 'index' %}">Home</a>
    <a href="{% url 'methods' %}">Methods</a>    
    <a class="active" href="{% url 'develop' %}">Develop</a>
    <a href="{% url 'theories' %}">Theories</a>
    <a href="{% url 'indicators' %}">Indicators</a>
    <a href="{% url 'strategies' %}">Strategies</a>     
{% endblock %}

{% block content %}
<div class="develop">
<div class="tab">
  <button rel="stocks" class="tablink active">Stocks</button>
  <button rel="strategy" class="tablink">DevelopStrategy</button>
  <button rel="analysis" class="tablink">Analyses</button>
</div>
  
<div id="stocks" class="tabcontent active">
  <div class="lside">
    <form>
      {% csrf_token %}
      {{ developInitialForm }}
      <br>
      <div id="symbolInput">
        <label>Add a symbol:</label>
        <input type="text" value="goog">
        <button type="button" id="startAdd">Start to add</button>
        <button type="button" id="addSymbol">Add</button>
      </div>
    </form>
    <div id="tablecontainer">
      <table>
        <tr class="headrow">
          <th>Symbol</th>
          <th>Delete</th>        
        </tr>
      </table>
    </div>
    <br>
    <div id="botButtons">
   <!--   <button type="button" id="id_save">Save</button> -->
   <!--   <button type="button" id="id_toggle">Toggle</button> -->
      <button type="button" id="id_reset">Reset</button>
  <!--    <select>Form</select> -->
    </div>
  </div>
  <div class="rside">
    <p>Stock Selector developing ...</p>
  </div>
</div>

<div id="strategy" class="tabcontent">
  <div class="lside">
    <p>Customized strategies developing</p>
  </div>
  <div class="rside">
    <form id="loadStrategy">
        {% csrf_token %}
        {{ selectStrategyForm.as_p }}
        <div class="button">
          <button type="button" id="submitSelectStrategy">Select</button>
        </div>
    </form>
    <form id="argInput">
    </form>
    <div id="submitPanel">
      <button type="button" id="startAnalyzing">Get Results</button>
      <p>Create analytical results for the strategy.</p>
    </div>
  </div>
</div>

<div id="analysis" class="tabcontent">
  <div id="resultTable">
    <table>

    </table>
  </div>

</div>



</div>
<script type="text/javascript">
var $start = $('#id_start');
var $end = $('#id_end');
var $interval = $('#id_interval');
var $symbol = $('#symbolInput input');

var stockSet = new Set([]);
var stockData = {};


$('#startAdd').on('click', function() {
  $(this).css({'display': 'none'});
  $('#addSymbol').css({'display': 'inline'});
  $start.attr('disabled', 'disabled');
  $end.attr('disabled', 'disabled');
  $interval.attr('disabled', 'disabled');
})

$('#addSymbol').on('click', function() {
  if (stockSet.has($symbol.val())) {
    alert('That stock has already been collected.');
  } else if ($symbol.val() === '') {
    alert('Error: Empty String Input');
  } else {
    var form = {
      symbol: $symbol.val(),
      start: $start.val(),
      end: $end.val(),
      interval: $interval.val(),
    };     
    $.ajax({
      type: 'POST',
      url: 'get-data',
      data: form,
      success: function(data){
        if (data.Close.length > 0) {
          stockData[$symbol.val().toUpperCase()] = data;            
          stockSet.add($symbol.val().toUpperCase());  
          $('#tablecontainer table').append(
            $("<tr></tr>").append(
                            $("<td></td>")
                              .text($symbol.val().toUpperCase())
                              .addClass("symbolText")
                            )
                          .append(
                            $("<td></td>").append(
                              $("<button></button>")
                                .text("delete")
                                .on('click', DeleteTr)
                            )
                          )
          );
        } else {
            alert('Suitable data not found. Please ensure the inputs are correct.');
        }
      $symbol.val('');
      $symbol.focus();
      },
      failure: function(data) {
        alert('Got an error');
      }
    } )
  }
})

function DeleteTr() {
  var $tr = $(this).closest('tr');
  var symbolText = $tr.find(".symbolText").text();
  delete stockData[symbolText];
  stockSet.delete(symbolText);
  $tr.remove();
}

$('#id_reset').on('click', function() {
  $('#tablecontainer table tr:not(:first-child)').each(function() {
    $(this).remove();
  })
  stockData = {};
  stockSet = new Set([]);
  $('#addSymbol').css({'display': 'none'});
  $('#startAdd').css({'display': 'inline'});
  $start.removeAttr('disabled');
  $end.removeAttr('disabled');
  $interval.removeAttr('disabled');
})

$('#loadStrategy button').on('click', function() {
  var $inputToUse = $('#loadStrategy select');
  var $Name = $inputToUse.val();
  var $Type = $inputToUse.attr('name');
  var form = {
    name: $Name,
    type: $Type, 
  };
  $.ajax({
    type: 'POST',
    url: 'get-method-arg',
    data: form,
    success: function(data){
      var arg = data.arg;
          
      for (i=0, len=arg.length; i<len; i++){
        $("<p></p>").attr('id', 'p_'+arg[i]).appendTo('#argInput');
        $("<label><label>")
          .attr('for', 'input_'+arg[i])
          .text(arg[i]+':')
          .css({'text-align': 'right', 'width': '120px', 'display': 'inline-block'})
          .appendTo('#p_'+arg[i]);
       
        $("<input type='text' value='' />")
          .attr('id', 'input_'+arg[i])
          .attr('name', arg[i])
          .css({'position': 'relative', 'left': '30px', 'width': '150px'})
          .appendTo('#p_'+arg[i]);   
      };
        
      $("<p></p>").attr('id', 'p_button')
          .appendTo('#argInput')
          .css({'position': 'relative', 'top': '15px'})
       
      $("<button type='button' id='resetRside'>Reset</button>")
          .appendTo('#p_button')    
          .css({'position': 'relative', 'left': '15px'});
        
      if (data.helpText) {
        helpText = data.helpText
        $("<div></div>").attr('id', 'helpText').appendTo('#argInput')
            .css({'position': 'relative', 'top': '25px'})
              
        for (i=0; i<helpText.length; i++) {
          $("<p></p>").appendTo('#helpText').text(helpText[i])     
        }     
      }
        
      $('#argInput').slideDown(250);
      $('#loadStrategy button').hide();
      $('#submitPanel').show(); 
      $inputToUse.attr('disabled', 'disabled');
      $('#resetRside').on('click', resetRside);
    },
    failure: function(data){
      alert('Got an error');
    }
  })
});

function resetRside(){
  $('#loadStrategy select').removeAttr('disabled');
  $('#loadStrategy button').show();   
  $('#argInput')
    .hide()
    .empty();
  $('#submitPanel').hide();
};

$('#startAnalyzing').on('click', function() {
  if (stockSet.size === 0) {
    alert('StockSet not created. Please collect stocks at relevant tab.');
  } else if ($('#argInput input').length > 0 && $('#argInput input').is(function() {
      return $(this).val() === "";
    })
  ) {
    alert('Please enter arguments needed for the strategy.');
  } else {
    $('.tablink.active').removeClass('active');
    $('.tablink[rel="analysis"]').addClass('active');
    $('.tabcontent.active').removeClass('active');
    $('#analysis').addClass('active');
    $('#resultTable table').empty();
     
    for (var stock in stockData) {
      if (stockData.hasOwnProperty(stock)) {
        var form = $.extend(true, {}, stockData[stock]);
                
        var $Name = $('#loadStrategy select').val();
        form['name'] = $Name;
        form['interval'] = $interval.val();
        form['symbol'] = stock;
        
        $('#argInput input').each(function() {
          form[$(this).attr('name')] = $(this).val();
        })
      
        $.ajax({
          type: 'POST',
          url: 'analyze-strategy',
          data: JSON.stringify(form),
          contentType: "application/json; charset=UTF-8",
      
          success: function(data) {
            if ($('#resultTable table tr').length === 0) {
              $curTr = $("<tr></tr>").appendTo('#resultTable table');
              for (var key in data) {
                if (data.hasOwnProperty(key)) {
                  $("<th></th>").text(key)
                                .appendTo($curTr);
                }
              }
            }
            $curTr = $("<tr></tr>").appendTo('#resultTable table');

            for (var key in data) {
              if (data.hasOwnProperty(key)) {
                $("<td></td>").text(data[key])
                              .appendTo($curTr);
              }
            }            
          },
          failure: function(data) {
            alert('Got an error');
          },
        })

      }
    }
    }

})

$.ajaxSetup({ 
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     } 
});

</script>

<script type="text/javascript">
$('.tablink').on('click', function() {
  var contentToShow = $(this).attr('rel');
  $('.tablink.active').removeClass('active');
  $(this).addClass('active');
  
  $('.tabcontent.active').removeClass('active');
  $('#'+ contentToShow).addClass('active');

})

</script>

   
{% endblock %}

main/templates/index.html
{% extends "base_generic.html" %}

{% block topnav %}
    <a class="active" href="{% url 'index' %}">Home</a>
    <a href="{% url 'methods' %}">Methods</a>
    <a href="{% url 'develop' %}">Develop</a>
    <a href="{% url 'theories' %}">Theories</a>
    <a href="{% url 'indicators' %}">Indicators</a>
    <a href="{% url 'strategies' %}">Strategies</a>   
{% endblock %}

{% block content %}
<div class="index">
<h1>Project: Stock Market Analysis</h1>

  <p>Welcome, this website is developed by <em>Xiao Han</em>.</p>

  <p>Building strategy development webpage ...</p>
  <p>Plan to save customized stock set/portfolio/strategy into database.</p>
  <p>Theories, Indicators, Strategies tabs are trivial.
   Pay your attention to <strong>Methods</strong> and <strong>Develop</strong> tabs.</p>
  <p><strong>Methods</strong>: Hopefully it will show you various indicators, strategies and analyses,
   which you could also apply on different stock and time period.</p>
  <p><strong>Develop</strong>: Create a stock set and input a time period,
   then pick a strategy and evaluate it.</p>
   
</div>

{% endblock %}

main/templates/indicator_generic.html
{% extends "base_generic.html" %}

{% block topnav %}
    <a href="{% url 'index' %}">Home</a>    
    <a href="{% url 'methods' %}">Methods</a>
    <a href="{% url 'develop' %}">Develop</a>
    <a href="{% url 'theories' %}">Theories</a>
    <a class="active" href="{% url 'indicators' %}">Indicators</a>
    <a href="{% url 'strategies' %}">Strategies</a>
{% endblock %}

main/templates/strategy_generic.html
{% extends "base_generic.html" %}

{% block topnav %}
    <a href="{% url 'index' %}">Home</a>    
    <a href="{% url 'methods' %}">Methods</a>
    <a href="{% url 'develop' %}">Develop</a>
    <a href="{% url 'theories' %}">Theories</a>
    <a href="{% url 'indicators' %}">Indicators</a>
    <a class="active" href="{% url 'strategies' %}">Strategies</a>
{% endblock %}

main/templates/theory_generic.html
{% extends "base_generic.html" %}

{% block topnav %}
    <a href="{% url 'index' %}">Home</a>    
    <a href="{% url 'methods' %}">Methods</a>
    <a href="{% url 'develop' %}">Develop</a>
    <a class="active" href="{% url 'theories' %}">Theories</a>
    <a href="{% url 'indicators' %}">Indicators</a>
    <a href="{% url 'strategies' %}">Strategies</a>
{% endblock %}